module.exports = {
    SUCCESS_CODE: 200,
    CREATED: 201,
    REQ_DATING_ERROR_CODE: 204,
    ERROR_CODE: 400,
    INVALID_CODE: 401,
    FORBIDDEN_CODE: 403,
    INACTIVATE: 406,
    NOT_FOUND: 404,
    CONFLICT: 409,
    SERVER_ERROR: 500,
    REQUEST_NOT_FOUND: "Request not found",
    EMAIL_ALREADY_REGISTERED: "Email already registered.",
    INVAILID_DATA: "Registration form data is not correct.",
    USER_SAVE_SUCCESS: "Registration completed successfully",
    USER_DELETED_SUCCESS: "User deleted successfully",
    USER_NOT_AUTHORIZED: "You are not Authorized",
    USER_RETRIEVE_SUCCESS: "User retrieve successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    USER_LOGIN_SUCCESS: "User Login successfully",
    USER_DATA_UPDATE_SUCCESS: "User update successfully",
    USER_VERIFICATION_SUCCESS: "User verified",
    USER_EMAIL_PASSWORD: "You have entered an invalid email or password",
    EMAIL_VERIFIED: "Email successfully verified.",
    EMAIL_NOT_VERIFIED: "Email Not verified.",
    INVALID_TOKEN: "Invalid Token",
    USER_EMAIL_NOT_REGISTERED: "This email is not registered.",
    SENT_FORGOT_EMAIL: "Email sent successfully.",
    USER_RESET_PASSWORD:
      "Reset password token expires! Regenerate token to set password",
    USER_OLD_PASSWORD: "User old password did not matched",
    PASSWORD_RESET: "Password reset successfully",
    OTP_VERIFICATION_SUCCESS: "OTP Verified successfuly",
    NOT_VAILID_OTP: "Please enter vailid otp",
    CATEGORY_SAVE_SUCCESS: "Product category created successfully",
    CATEGORY_UPDATED_SUCCESS: "Product category updated successfully",
    CATEGORY_DELETED_SUCCESS: "Product category deleted successfully",
    CATEGORY_RETRIEVE_SUCCESS: "Product category retrieve successfully",
    NO_DATA_FOUND: "No data found",
    PAYMENT_UPDATED_SUCCESS: "Payment updated successfully",
    PAYMENT_RETRIEVE_SUCCESS: "Payment retrieve successfully",
    CART_SAVE_SUCCESS: " Cart created successfully",
    CART_DELETED_SUCCESS: "Cart deleted successfully",
    CART_RETRIEVE_SUCCESS: "Cart data retrieve successfully",
    CART_DATA_DELETED_SUCCESS: "Cart data deleted successfully",
    CART_DATA_UPDATED_SUCCESS: " Cart data updated successfully",
    FAVCART_SAVE_SUCCESS: "Liked successfully",
    DATA_SAVED_SUCCESS: "Data saved successfully",
    DATA_DELETED_SUCCESS: "Data deleted successfully",
    DATA_UPDATED_SUCCESS: "Data updated successfully",
    DATA_RETRIEVED_SUCCESS: "Data retrieved successfully",
    CATEGORY_SAVED_SUCCESS: " Category created successfully",
    CATEGORY_UPDATE_SUCCESS: " Category updated successfully",
    CATEGORY_DELETE_SUCCESS: "Category deleted successfully",
    CATEGORY_RETRIEVED_SUCCESS: "Category retrieve successfully",
    SHOP_SAVE_SUCCESS:"Shop created successfully",
    SHOP_UPDATE_SUCCESS:"Shop updated successfully",
    SHOP_DELETED_SUCCESS:"Shop deleted successfully",
    SHOP_RETRIEVE_SUCCESS:"Shop retrive successfully"
  };
  